# ====================================================================
# APT File Server — Windows Event Log Collection Script
# Generated by collect_logs.py
# Target: Event IDs 4624, 4625, 4648, 4656, 4658, 4660, 4663, 4688, 4698, 5140, 5145, 7045, 1102 from the last 1 day(s)
# ====================================================================

$ErrorActionPreference = 'SilentlyContinue'

# Time filter: last 1 day(s)
$StartTime = (Get-Date).AddDays(-1)

Write-Host "[*] Thu thap log tu Security log..." -ForegroundColor Cyan
Write-Host "[*] Event IDs: 4624, 4625, 4648, 4656, 4658, 4660, 4663, 4688, 4698, 5140, 5145, 7045, 1102" -ForegroundColor Cyan
Write-Host "[*] Tu: $StartTime den: $(Get-Date)" -ForegroundColor Cyan

# Query with FilterHashtable (optimized at the API level)
$Events = Get-WinEvent -FilterHashtable @{
    LogName   = 'Security'
    ID        = 4624, 4625, 4648, 4656, 4658, 4660, 4663, 4688, 4698, 5140, 5145, 7045, 1102
    StartTime = $StartTime
} -ErrorAction SilentlyContinue

if (-not $Events -or $Events.Count -eq 0) {
    Write-Host "[!] CANH BAO: Khong tim thay event nao!" -ForegroundColor Yellow
    Write-Host "[!] Kiem tra:" -ForegroundColor Yellow
    Write-Host "    1. Script dang chay voi quyen Administrator" -ForegroundColor Yellow
    Write-Host "    2. Audit Policy da duoc bat:" -ForegroundColor Yellow
    Write-Host "       auditpol /set /subcategory:'File System' /success:enable /failure:enable" -ForegroundColor Yellow
    Write-Host "       auditpol /set /subcategory:'Detailed File Share' /success:enable /failure:enable" -ForegroundColor Yellow
    Write-Host "    3. SACL da duoc cau hinh tren thu muc can giam sat" -ForegroundColor Yellow
    exit 1
}

Write-Host "[+] Tim thay $($Events.Count) events!" -ForegroundColor Green

# Parse each event's XML to extract detailed fields
$ParsedEvents = @()
$Counter = 0

foreach ($Event in $Events) {
    $Counter++
    if ($Counter % 500 -eq 0) {
        Write-Host "[*] Dang xu ly: $Counter / $($Events.Count)..." -ForegroundColor Gray
    }

    # Parse the event XML
    [xml]$XmlData = $Event.ToXml()
    $EventData = @{}

    # Extract all <Data Name="..."> elements from <EventData>
    $XmlData.Event.EventData.Data | ForEach-Object {
        if ($_.Name) {
            $EventData[$_.Name] = $_.'#text'
        }
    }

    # Build the standardized record
    $Record = [PSCustomObject]@{
        TimeCreated       = $Event.TimeCreated.ToString('o')
        EventID           = $Event.Id
        SubjectUserSid    = $EventData['SubjectUserSid']
        SubjectUserName   = $EventData['SubjectUserName']
        SubjectDomainName = $EventData['SubjectDomainName']
        SubjectLogonId    = $EventData['SubjectLogonId']
        ObjectServer      = $EventData['ObjectServer']
        ObjectType        = $EventData['ObjectType']
        ObjectName        = $EventData['ObjectName']
        HandleId          = $EventData['HandleId']
        AccessList        = $EventData['AccessList']
        AccessMask        = $EventData['AccessMask']
        ProcessId         = $EventData['ProcessId']
        ProcessName       = $EventData['ProcessName']
        ShareName         = $EventData['ShareName']
        ShareLocalPath    = $EventData['ShareLocalPath']
        RelativeTargetName = $EventData['RelativeTargetName']
        IpAddress         = $EventData['IpAddress']
        IpPort            = $EventData['IpPort']
        MachineName       = $Event.MachineName
        LogName           = $Event.LogName
    }

    $ParsedEvents += $Record
}

Write-Host "[+] Da xu ly xong $($ParsedEvents.Count) events." -ForegroundColor Green

        # Export to JSON (depth 5 for nested structures)
        $ParsedEvents | ConvertTo-Json -Depth 5 | Out-File -FilePath 'C:\Users\laptopJP.vn\Desktop\APT-opus\full_logs.json' -Encoding UTF8
        Write-Host "[+] Da xuat ra JSON: C:\Users\laptopJP.vn\Desktop\APT-opus\full_logs.json" -ForegroundColor Green
        
        # Summary statistics
        Write-Host ""
        Write-Host "=== THONG KE ===" -ForegroundColor Cyan
        $ParsedEvents | Group-Object EventID | ForEach-Object {
            Write-Host "  Event $($_.Name): $($_.Count) records" -ForegroundColor White
        }

        # User summary
        Write-Host ""
        Write-Host "=== NGUOI DUNG ===" -ForegroundColor Cyan
        $ParsedEvents | Group-Object SubjectUserName | Sort-Object Count -Descending | Select-Object -First 10 | ForEach-Object {
            Write-Host "  $($_.Name): $($_.Count) events" -ForegroundColor White
        }

        Write-Host ""
        Write-Host "[+] HOAN THANH! File log da san sang de phan tich." -ForegroundColor Green
    