"""
=============================================================================
File Server UEBA — LLM Advisor
=============================================================================

Provides AI-powered natural-language analysis of per-user anomaly results.
Mirrors the pattern of webserver_module_AIT/final_layer/llm_advisor.py but
adapted for the File Server UEBA domain (Windows Event Logs, Isolation Forest
scores, 25 behavioral features across 6 dimensions).
"""

import json
import requests


class FileServerLLMAdvisor:
    """Generates LLM-based threat analysis for file server UEBA results."""

    def __init__(self):
        self.GOOGLE_URL = (
            "https://generativelanguage.googleapis.com/v1beta/models/"
            "{model}:generateContent?key={api_key}"
        )
        self.OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
        self.NVIDIA_URL = "https://integrate.api.nvidia.com/v1/chat/completions"

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _build_prompt(self, user_result: dict) -> str:
        """Build a structured threat-analysis prompt from a user result dict."""

        user = user_result.get("user", "UNKNOWN")
        status = user_result.get("status", "unknown")
        max_score = user_result.get("max_score", 0)
        avg_score = user_result.get("avg_score", 0)
        anomaly_count = user_result.get("anomaly_count", 0)
        total_windows = user_result.get("total_windows", 0)

        if max_score >= 80:
            threat_label = "CRITICAL"
        elif max_score >= 50:
            threat_label = "WARNING"
        else:
            threat_label = "NORMAL"

        prompt = (
            "You are a Senior SOC Analyst and APT (Advanced Persistent Threat) Expert "
            "specialising in Windows File Server forensics.\n"
            "You are reviewing a UEBA (User and Entity Behavior Analytics) anomaly report "
            "generated by an Isolation Forest model trained on this user's own historical baseline.\n\n"
            "Your task:\n"
            "1. Determine if this is a TRUE POSITIVE (real attack) or BENIGN anomaly.\n"
            "2. If attack: classify the type (Ransomware, Data Exfiltration, Insider Threat, "
            "Brute-Force, Lateral Movement, Persistence, Anti-Forensics, etc.).\n"
            "3. Identify the APT kill-chain stage(s) involved.\n"
            "4. Explain the attacker's methodology based on the behavioral features.\n"
            "5. Provide recommended SOC response actions.\n\n"
            "Answer precisely, shortly and go straight to the point in Vietnamese.\n\n"
        )

        # Section 1: General Profile
        prompt += "[1. HỒ SƠ TỔNG QUAN]\n"
        prompt += f"Người dùng: {user}\n"
        prompt += f"Mức Đe Dọa: {threat_label} (Điểm Max: {max_score}/100, Điểm TB: {avg_score}/100)\n"
        prompt += f"Cửa sổ Dị thường: {anomaly_count}/{total_windows}\n"
        prompt += f"Trạng thái: {status}\n\n"

        # Section 2: Full Feature Context
        feature_values = user_result.get("feature_values", {})
        if feature_values:
            prompt += "[2. ĐẶC TRƯNG HÀNH VI CHI TIẾT (25 features từ Isolation Forest)]\n"
            prompt += "Các giá trị sau là giá trị MAX qua tất cả các cửa sổ thời gian:\n"

            # Group features by category for readability
            categories = {
                "Volume / Velocity": [
                    "total_read_operations", "total_write_operations",
                    "total_delete_operations", "total_events", "read_write_ratio",
                ],
                "Variety / Context": [
                    "distinct_files_accessed", "distinct_processes_used",
                    "admin_share_access_count", "lolbin_event_count",
                ],
                "Spatio-Temporal": [
                    "off_hour_activity_ratio", "hour_sin", "hour_cos",
                ],
                "Authentication": [
                    "successful_logon_count", "failed_logon_count",
                    "failed_logon_ratio", "distinct_logon_source_ips",
                    "explicit_credential_count",
                ],
                "Process Execution": [
                    "new_process_count", "suspicious_process_count",
                    "distinct_parent_processes",
                ],
                "Persistence": [
                    "scheduled_task_created_count", "service_installed_count",
                ],
                "Anti-Forensics": [
                    "audit_log_cleared_count", "object_deleted_count",
                ],
                "Network / Share": [
                    "share_session_count", "distinct_shares_accessed",
                ],
            }

            for cat_name, feat_list in categories.items():
                prompt += f"\n  [{cat_name}]\n"
                for feat in feat_list:
                    val = feature_values.get(feat, 0)
                    if isinstance(val, float):
                        prompt += f"  - {feat}: {val:.4f}\n"
                    else:
                        prompt += f"  - {feat}: {val}\n"
            prompt += "\n"

        # Section 3: Top Deviating Features
        top_features = user_result.get("top_features", [])
        if top_features:
            prompt += "[3. TOP 5 ĐẶC TRƯNG LỆCH CHUẨN NHẤT (Z-Score so với Baseline)]\n"
            for feat in top_features:
                prompt += (
                    f"  - {feat['feature']}: Z={feat['z_deviation']:.2f} "
                    f"(Baseline Mean={feat['training_mean']:.2f}, "
                    f"Std={feat['training_std']:.2f}, "
                    f"Current={feat['current_value']:.2f})\n"
                )
            prompt += "\n"

        # Section 4: Anomaly Timeline
        scores = user_result.get("scores", [])
        anomalous_windows = [s for s in scores if s.get("is_anomaly")]
        if anomalous_windows:
            prompt += "[4. CÁC CỬA SỔ DỊ THƯỜNG]\n"
            for w in anomalous_windows[:20]:  # Limit to avoid token overflow
                prompt += f"  - {w['time_window']}: Score={w['anomaly_score']}\n"
            if len(anomalous_windows) > 20:
                prompt += f"  ... và {len(anomalous_windows) - 20} cửa sổ khác\n"
            prompt += "\n"

        return prompt

    # ------------------------------------------------------------------
    # LLM API Calls (same pattern as webserver module)
    # ------------------------------------------------------------------

    def _call_openai_compatible(self, url, prompt, model, api_key):
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        if "openrouter" in url:
            headers["HTTP-Referer"] = "https://github.com/your-repo/apt-hunter"
            headers["X-Title"] = "APT Hunter System"

        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a direct cybersecurity AI."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.08,
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=60)
            if response.status_code == 200:
                return response.json()["choices"][0]["message"]["content"]
            return f"API Error {response.status_code}: {response.text}"
        except Exception as e:
            return f"Connection Error: {e}"

    def _call_google(self, prompt, model, api_key):
        url = self.GOOGLE_URL.format(model=model, api_key=api_key)
        headers = {"Content-Type": "application/json"}

        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.08},
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=60)
            if response.status_code == 200:
                return response.json()["candidates"][0]["content"]["parts"][0]["text"]
            return f"API Error {response.status_code}: {response.text}"
        except Exception as e:
            return f"Connection Error: {e}"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze_user(self, user_result: dict, provider: str, model: str, api_key: str) -> str:
        """
        Analyze a user's anomaly results using an LLM.

        Args:
            user_result: A single user dict from analysis_results.json['user_results'].
            provider: 'nvidia', 'openrouter', or 'google'.
            model: Model name (e.g. 'meta/llama3-70b-instruct').
            api_key: API key for the provider.

        Returns:
            LLM-generated analysis string.
        """
        if not api_key:
            return "[-] Vui lòng cung cấp API Key trong phần Cài đặt."

        prompt = self._build_prompt(user_result)

        if provider.lower() == "openrouter":
            return self._call_openai_compatible(self.OPENROUTER_URL, prompt, model, api_key)
        elif provider.lower() == "nvidia":
            return self._call_openai_compatible(self.NVIDIA_URL, prompt, model, api_key)
        elif provider.lower() == "google":
            return self._call_google(prompt, model, api_key)
        else:
            return "[-] Error: Unknown provider."
